name: lintWorkflows

on:
   push:
   pull_request:
   workflow_dispatch:

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    container:
      image: returntocorp/semgrep:1.1.0
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v3
      
      - name: "Execute semgrep"
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: p/default
  hadolint:
    name: "Hadolint scan"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    # don't execute this workflow for dependabot pr
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Run hadolint"
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
