name: lintWorkflows

on:
   push:
   pull_request:

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    container: # Use a container
      image: returntocorp/semgrep:1.1.0
    # don't execute this workflow for dependabot pr
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v3
      
      - name: "Execute semgrep"
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          # Specify the ruleset to use
          SEMGREP_RULES: p/default

