name: test workflows

on:
  push:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.17','1.18','1.19'] #on crée un tableau contenant toutes les versions

    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go ${{matrix.go-version}} #configuration des environnement go avec chaque version du tableau go-version
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
      
      - name: build 
        run: go build ./...
      
      - name: test ${{matrix.go-version}} # on exécute la commande go test ./...
        run: go test ./...